### ISSUE TITLE
Problem of stacking masks 

### ISSUE THREAD

**Issue by BigeyeDestroyer** [interactiveaudiolab/nussl#100]
#### Description
There is a problem of stacking the calculated masks for each source from different channels in line 198 of function `nmf_mfcc'.

#### Steps/Code to Reproduce
The original code is:
```python
collated_masks = [np.dstack([uncollated_masks[ch + s * n_chan] for ch in range(n_chan)]) for s in range(self.num_sources)]
```
But I think the right version should be:
```python
collated_masks = [np.dstack([uncollated_masks[s + ch * self.num_sources] for ch in range(n_chan)]) for s in range(self.num_sources)]
```

#### Expected Results
When we mix two sources and separate them with the NMF method, we should get different masks.

#### Actual Results
With the wrong code, the estimated masks of two sources are the same.

**Comment by ethman** [comment]
Hey @BigeyeDestroyer, thanks for stress testing this code! Yeah, it looks like the loop variables are incorrect there. I'll push this fix as well as #99, when I figure out #97.

**Comment by BigeyeDestroyer** [comment]
You are welcome !

**Comment by pseeth** [comment]
NMF_MFCC was moved to TimbreClustering in v1.0.0 of nussl. Should be fixed now.
