### ISSUE TITLE
Fatemeh's name is spelled incorrectly in the README

### ISSUE THREAD

**Issue by BrianMargolis** [interactiveaudiolab/nussl#116]
#### Description
Fatemeh is spelled as "Fatemah" in README.md, both under "Citing" and "Contributors"

#### Steps/Code to Reproduce
N/A

#### Expected Results
Fatemeh

#### Actual Results
Fatemah

#### Versions
N/A

**Comment by pseeth** [comment]
Thanks Brian! And sorry Fatemeh! Double thanks to your strict adherence to the guidelines for reporting bugs. ;)
