### ISSUE TITLE
other required dependencies unmentioned in getting started

### ISSUE THREAD

**Issue by jsphweid** [interactiveaudiolab/nussl#125]
I followed this guide: https://interactiveaudiolab.github.io/nussl/getting_started/install.html. It was mostly helpful but I kept getting errors when trying to `import nussl` until I installed 2 other dependencies:

```
pip install musdb
pip install museval
```

I don't use python often and consequently don't have a good grasp on how it manages dependencies. Maybe those were supposed to be auto-installed when I did `pip install nussl`? Or maybe one must manually do that and it's simply not well-documented?

Just thought I'd point it out in case anyone else was confused.

**Comment by interactiveaudiolab** [comment]
Yes, Ethan. This seems like a small fix. So....you know...fix it.

**Comment by lordB8r** [comment]
I'm also hitting his bug (it's been a few months). Do you need a pull request to update the docs?

**Comment by pseeth** [comment]
This stuff should be fixed now. Sorry about that!
