### ISSUE TITLE
NUSSL module has no attribute NMF_MFCC

### ISSUE THREAD

**Issue by conwayzhu** [interactiveaudiolab/nussl#129]
#### Description

Running the NMF MFCC example gives the error 
`AttributeError: 'module' object has no attribute 'NMF_MFCC'`
#### Steps/Code to Reproduce

Just running the example code given [here](https://interactiveaudiolab.github.io/nussl/examples/nmf_mfcc_demo.html) 
#### Actual Results

`   
AttributeError: 'module' object has no attribute 'NMF_MFCC'
`
#### Versions

NUSSL version 0.1.5a10, Python 2.7.13

**Comment by ethman** [comment]
Hi conwayzhu, does this problem still exist in nussl version 0.1.6?

**Comment by ethman** [comment]
I'm going to close this due to lack of activity. Feel free to reopen it if the problem persists.
