### ISSUE TITLE
module 'nussl' has no attribute 'AudioSignal'

### ISSUE THREAD

**Issue by ericye16** [interactiveaudiolab/nussl#133]
#### Description

When I import nussl and run:
```python
history = nussl.AudioSignal('HistoryRepeatingPropellerHeads.wav')
```

It gives me the error in the title.

#### Steps/Code to Reproduce

see above

#### Expected Results

No error occurs

#### Actual Results

This output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'nussl' has no attribute 'AudioSignal'
```

#### Versions

```
import platform; print(platform.platform())
Darwin-18.2.0-x86_64-i386-64bit
>>> import sys; print("Python", sys.version)
Python 3.7.1 (default, Nov  6 2018, 18:46:03) 
[Clang 10.0.0 (clang-1000.11.45.5)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.15.4
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.2.0
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 0.20.2
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.2
>>> import nussl; print("nussl", nussl.__version__)
```

**Comment by pseeth** [comment]
First, if you're using the nussl master branch, it won't work with Python 3 as far as I know. We're working on updating to Python 3. And also, yes it seems that AudioSignal is not in __all__ for some reason! Wonder how that happened. An easy fix though, and you've done it already!

Thanks!

**Comment by ericye16** [comment]
I was using the `train` branch which I saw from the other issue was expected to work in python3?

**Comment by pseeth** [comment]
Oh great. Yes it does. If you hold up for a bit, I'm about to commit stuff into that branch (actual training code) and can include this fix!

**Comment by pseeth** [comment]
Pushed! It still needs documentation but it all works right now.

**Comment by pseeth** [comment]
I just noticed that the documentation also makes reference to things like `nussl.Repet` which doesn't exist in __all__. I got rid of __all__ in the top level. That documentation should work now.

**Comment by ericye16** [comment]
Yeah, I just noticed that too. Thanks for responding so quickly!

**Comment by pseeth** [comment]
Should be fixed now in the pip install.
