### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by shauryad15** [interactiveaudiolab/nussl#135]
#### Description
Import error: While importing nussl

#### Steps/Code to Reproduce
 1 import nussl

~\AppData\Local\Continuum\miniconda3\envs\ge_hrsg\lib\site-packages\nussl\__init__.py in <module>()
     24 
     25 
---> 26 from .core.constants import *
     27 from .core.audio_signal import AudioSignal
     28 from .core import utils, efz_utils, stft_utils, datasets

~\AppData\Local\Continuum\miniconda3\envs\ge_hrsg\lib\site-packages\nussl\core\__init__.py in <module>()
     from audio_signal import AudioSignal
      

ModuleNotFoundError: No module named 'audio_signal'-->

#### Versions
Please run the following snippet and paste the output below.
>>> import platform; print(platform.platform())
Windows-10-10.0.16299-SP0
>>> import sys; print("Python", sys.version)
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.14.5
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.1.0
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 0.19.1
>>> import librosa; print("librosa", librosa.__version__)
librosa 0.6.2
>>> import nussl; print("nussl", nussl.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\shaurya.dwivedi\AppData\Local\Continuum\miniconda3\envs\ge_hrsg\lib\site-packages\nussl\__init__.py", line 26, in <module>
    from .core.constants import *
  File "C:\Users\shaurya.dwivedi\AppData\Local\Continuum\miniconda3\envs\ge_hrsg\lib\site-packages\nussl\core\__init__.py", line 7, in <module>
    from audio_signal import AudioSignal
ModuleNotFoundError: No module named 'audio_signal'

**Comment by pseeth** [comment]
Seems you are using Python 3? nussl on the master branch is not ready for Python 3. nussl on the train branch is though, if you want to use that instead.
