### ISSUE TITLE
[train] Naming collision wrt datasets

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/nussl#146]
In the `train` branch, there's implementations following pytorch's `Dataset` mixing API in `nussl.deep.datasets`. Because they have different uses, I'm concerned that the name matches nussl's dataset hooks in `nussl.core.datasets`. I think both of these probably need more descriptive names. Perhaps `nussl.deep.training_dataset` or `nussl.deep.dataset_mixin` for the former, and `nussl.core.dataset_hooks` for the latter?

Thoughts? Opinions?

**Comment by pseeth** [comment]
Fixed! The two classes have now been merged into one.
