### ISSUE TITLE
Test case documentation

### ISSUE THREAD

**Issue by maxrmorrison** [interactiveaudiolab/nussl#149]
#### Description
The process of running test cases should have some form of documentation, even if it's just `python -m unittest discover` in the root directory. The `train` branch currently produces an error due to a module import. Specifically, `ModuleNotFoundError: No module named 'benchmark_test_base'`. Commenting out the import statement in `tests/__init__.py` seems to fix the issue and allows tests to be run.

**Comment by pseeth** [comment]
It's just `pytest` now, and is documented. Thanks!
