### ISSUE TITLE
Remove relative paths in test cases

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/nussl#150]
Use the EFZ instead, all of these files should be up there already.

Offenders:

- "/homes/manilow/Desktop/nussl/nussl/tests/test_run_and_eval.py", line 16, in test_simple
- "/homes/manilow/Desktop/nussl/nussl/tests/test_json.py", line 52, in test_repet_sim
- "/homes/manilow/Desktop/nussl/nussl/tests/test_json.py", line 30, in test_repet
- "/homes/manilow/Desktop/nussl/nussl/tests/test_json.py", line 41, in test_duet
- "/homes/manilow/Desktop/nussl/nussl/tests/test_json.py", line 13, in test_audio_signal
- "/homes/manilow/Desktop/nussl/nussl/tests/test_precision_recall_fscore.py", line 22, in test_simple

**Comment by pseeth** [comment]
Fixed.
