### ISSUE TITLE
Dynamically check for nimfa when running NMF tests

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/nussl#151]
For the NMF tests, we benchmark our implementation against `nimfa`, but it's not an official nussl dependency. When running the test suite the NMF test fail, but they should just be skipped in `nimfa` isn't installed. 

https://docs.python.org/2.7/library/unittest.html#skipping-tests-and-expected-failures

    try:
        import nimfa
        nimfa_avail = True
    except ModuleImportError:
        nimfa_avail = False
    
    @unittest.skipUnless(nimfa_avail, "No nimfa")
     def nmf_test_case():
          bla_blah = "wow, what a great test!"

**Comment by pseeth** [comment]
Not using nimfa anymore, so can close this.
