### ISSUE TITLE
musdb 0.3.0 was released

### ISSUE THREAD

**Issue by faroit** [interactiveaudiolab/nussl#155]
Hey nussl people,

we just [released musdb 0.3.0](https://github.com/sigsep/sigsep-mus-db/releases/tag/v0.3.0) that brought a few changes. I quickly checked where you use `musdb` in nussl and didn't found things that would break, but maybe its better to changed the requirements to `==0.2.3` for now until things are checked.

Cheers

**Comment by ethman** [comment]
Awesome. Thanks for the heads up. We'll check it out and get things updated on our end!

**Comment by faroit** [comment]
if you upgrade, make sure you use `0.3.0.post1` ;-)

**Comment by faroit** [comment]
Also museval 0.3.0 is in beta. Check it out ;-)

**Comment by faroit** [comment]
update: its `0.3.0` is released

**Comment by pseeth** [comment]
MUSDB works to great effect in nussl now. Super useful for making test cases with that automatic downloading stuff, thank you @faroit!
