### ISSUE TITLE
bsseval scores for deep clustering results

### ISSUE THREAD

**Issue by faroit** [interactiveaudiolab/nussl#156]
Hi nusslers, do you have the results of the pretrained deep clustering model on MUSDB18 somewhere?

**Comment by pseeth** [comment]
Using museval SDR or SI-SDR? I have the SI-SDR results for vocals/accompaniment separation somewhere...but will take a little bit to get them to you. Though I've noticed that the SD-SDR (scale-dependent SDR) results seem to make more sense...I think I can get to this in September if that's alright? For museval, it takes quite a bit of computational resources so that'll take a little longer. For 4-way classification (bass, drums, other, vocals) I'll have to train a new model.

**Comment by faroit** [comment]
cool. Did you remember if it was in the ballpark of UHL1 or significantly better?

**Comment by pseeth** [comment]
Oh, the results I got were below UHL1, I think. I have 3.84 dB SD-SDR sitting around for vocals/accompaniment. And in my paper from last ICASSP, I have some results for DPCL + GMM (chimera-net like stuff): https://pseeth.github.io/public/papers/seetharaman_class_icassp19.pdf.

The results in that paper are using museval.

**Comment by pseeth** [comment]
I think you need some Chimera-net stuff to get high SDRs for deep clustering on music. Deep clustering uses an IBM for training so the results usually have lower SAR.

**Comment by faroit** [comment]
yes, I was expecting this. 

>  I have some results for DPCL + GMM (chimera-net like stuff): https://pseeth.github.io/public/papers/seetharaman_class_icassp19.pdf.

are the results in the table median of median? or median of means?

**Comment by pseeth** [comment]
I used this repo for all the analysis: https://github.com/sigsep/sigsep-mus-2018-analysis if i recall correctly. I modified the notebook. So median of nanmedians, I believe.

**Comment by faroit** [comment]
thanks for the info. In the meantime, we [released the pytorch version of open-unmix](https://github.com/sigsep/open-unmix-pytorch). The scores on the readme are median of medians. I think we should have been more clear about these aggreations in the SiSEC papers. I see lots of papers now that just give the scores without specifying the aggregation functions.

In the just released version of museval 0.3.0 I now set the defaults to median of medians but if can easily be [changed](https://github.com/sigsep/sigsep-mus-eval/blob/master/museval/aggregate.py#L169). 

@pseeth feel free to drop us some comments over the new version.
