### ISSUE TITLE
Documentation - REPET class does not properly show expected input

### ISSUE THREAD

**Issue by kmads** [interactiveaudiolab/nussl#39]
You describe the parameters, whether or not they are optional, and what the default values are below the class. The class instantiation itself does not have this information, and instead makes it look like every parameter is optional and defaulted to None:
<img width="521" alt="screen shot 2016-04-14 at 8 34 08 am" src="https://cloud.githubusercontent.com/assets/10760012/14529784/c5e03b5a-021b-11e6-8efc-ab8b28f80db8.png">
Instead, you should show which parameters the user must use, as well as those that are optional and given a default value:
`class Repet.Repet(input_audio_signal, sample_rate, stft_params, repet_type, similarity_threshold=0, min_distance_between_frames=1, max_repeating_frames=10, min_period=0.8, max_period=min(8, self.Mixture.SignalLength/3), period=None, high_pass_cutoff=100)`

Note: I'm not sure if you can set such a default value to max_period. If not, you could probably just do something like: `max_period='default_max'`, and then inside the class, do: `if max_period=='default_max': max_period=min(8, self.Mixture.SignalLength/3)`.

In addition, I followed the Repet demo code, and it shows instantiating the Repet class with only the signal as an input. If I provide only the signal, and ignore the stft_params section below the class instantiation and above repet.run(), everything still runs fine. Repet clearly has defaults for everything except input_audio_signal, including the parameters that did not seem to be optional, such as sample_rate, stft_params, repet_type. You should indicate the default values in the parameter descriptions.
- Does sample_rate automatically get tracked from the input_audio_signal?
- What are the WindowAttributes? Is that a class? Why isn't it clickable? What can you do with it?
- I see that repet_type allows you to click on RepetType, which then takes you to the corresponding section on the page, showing that the default value is "original". This is not immediately obvious that repet_type is set to a default of "original" in the Repet class instantiation.

**Comment by interactiveaudiolab** [comment]
This is no longer relevant.
