### ISSUE TITLE
Documentation - REPET class static function clarification

### ISSUE THREAD

**Issue by kmads** [interactiveaudiolab/nussl#44]
Are the static functions in the REPET class meant for users, or are those functions you call only internally in your code? For example: I am unsure how to call `static compute_beat_spectrum(X)` because I don't know how to generate the autocorrelation matrix X. 

At first I thought I had to use `static compute_beat_spectrum(X)` in order to generate the beat spectrum for my Repet object, especially since it is the first function listed on the page. However, I scrolled down and saw that `get_beat_spectrum()` was what I wanted. The same goes for `static compute_similarity_matrix(X)` and `get_similarity_matrix()`.

Are your static functions supposed to be accessible to the public? Do they allow a user to have more control over how the similarity matrix, beat spectrum, etc. are computed by the system? Or are they only intended to be called within the program by the system? If it's the former, you should explain how users should use these functions correctly (and with the correct input). If it's the latter, you should remove these from the documentation.

You should also probably put the most important/useful/probably-commonly-used functions at the top of the page, such as self.run(), self.get_beat_spectrum(), self.get_similarity.matrix(), and self.plot(...).

**Comment by ethman** [comment]
Fixed with documentation update a few weeks ago.
