### ISSUE TITLE
[AudioSignal] when adding/subtracting two signals of different length show warning/error

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/nussl#74]

**Comment by pseeth** [comment]
I think it should be an error, now that I think on it some more. Should be a show-stopper and alert the user that something's off. Especially when doing algorithm development for nussl.

**Comment by ethman** [comment]
Yeah, but what if I want to create a mixture of multiple signals?

**Comment by pseeth** [comment]
You could make use of the zero_pad functions explicitly first before adding them? or the truncate_samples, or crop_signals. Maybe add a function that's like append_zeros?

**Comment by ethman** [comment]
So I think it might be best to have two functions, one for strict arithmetic (which would be +, - operators and AudioSignal.add(), etc) that asserts that the signals are of equal length and also another one for adding signals with mismatched length as a separate utility.

**Comment by ethman** [comment]
closed. Add, subtract now require stricter rules. Adding a new feature request for the loosey goosey add/sub.

**Comment by ethman** [comment]
In development branch
