### ISSUE TITLE
Documentation - RepetSim has code for Repet

### ISSUE THREAD

**Issue by tuchandra** [interactiveaudiolab/nussl#76]
The two examples on the [RepetSim](https://interactiveaudiolab.github.io/nussl/src/repet_sim.html) class page mistakenly duplicates the code from the [Repet](https://interactiveaudiolab.github.io/nussl/src/repet.html) class. 

Both instances of
```
# Set up a Repet object
repet = nussl.Repet(signal)
```
(under [get_similarity_matrix()](https://interactiveaudiolab.github.io/nussl/src/repet_sim.html#repet_sim.RepetSim.get_similarity_matrix) and [make_audio_signals()](https://interactiveaudiolab.github.io/nussl/src/repet_sim.html#repet_sim.RepetSim.make_audio_signals)) should read

```
# Set up a Repet object
repet = nussl.RepetSim(signal)
```

**Comment by ethman** [comment]
Yeah, looks like the documentation needs to be beefed up for RepetSim
