### ISSUE TITLE
AudioSignal: doesn't resample audio if you pass in sample_rate as an argument to it.

### ISSUE THREAD

**Issue by pseeth** [interactiveaudiolab/nussl#77]
It always will give you the sampling rate of the input file instead of the sample rate you requested. Behavior should be that if you don't give it a sample rate, it gives you the sample rate of the file. If you do give it a sample rate, it should resample the audio.

**Comment by ethman** [comment]
Related to #70

**Comment by ethman** [comment]
Here's a solution I'm thinking about for this, I'm curious for your input @pseeth. sample_rate is only settable on init or by calling `signal.resample(new_sr)`. So now `signal.sample_rate` is a read-only property and the only ways to set it are `signal.load_audio_from_file`, `signal.load_audio_from_array` (both of which get called in the constructor), or `signal.resample`. With initializing with STFT data, the user would have to add `sample_rate` as an input parameter. Thoughts?

**Comment by ethman** [comment]
In dev
