### ISSUE TITLE
demo_duet.py file

### ISSUE THREAD

**Issue by anasvaf** [interactiveaudiolab/nussl#78]
Hi, 
I am trying to execute the demo_duet.py file as is (input file "FEMALE MIXTURE".
However, I get the following error:
Traceback (most recent call last):
  File "demo_duet.py", line 34, in <module>
    main()
  File "demo_duet.py", line 18, in main
    duet.run()
  File "/usr/local/lib/python2.7/dist-packages/nussl/Duet.py", line 103, in run
    L, hop, winType, fs, use_librosa=True)
TypeError: e_stft_plus() got an unexpected keyword argument 'use_librosa'

I edit the Duet.py lines 101-109 with the following
        # Compute the stft of the two channel mixtures
        stft1, psd1, frequency_vector, time_vector = spectral_utils.e_stft_plus(self.audio_signal.get_channel(1),
                                                                                L, hop, winType, fs, **_remove_reflection=False)_**
        stft2, psd2, frequency_vector, time_vector = spectral_utils.e_stft_plus(self.audio_signal.get_channel(2),
                                                                                L, hop, winType, fs, **_remove_reflection=False_**)

and then I get the following error:

Traceback (most recent call last):
  File "demo_duet.py", line 34, in <module>
    main()
  File "demo_duet.py", line 18, in main
    duet.run()
  File "/usr/local/lib/python2.7/dist-packages/nussl/Duet.py", line 125, in run
    delta = -np.imag(np.log(R21)) / (2 * np.pi * wmat)  # relative delay
ValueError: operands could not be broadcast together with shapes (2047,2215) (2048,2215) 

Could I get some help with that?

Thank you in advance!
- Tasos

**Comment by ethman** [comment]
This is fixed in the master branch now. There won't be another pip update for a few weeks so if you need this pull from github.

**Comment by anasvaf** [comment]
Thank you!
