### ISSUE TITLE
Plotting functionality should be different

### ISSUE THREAD

**Issue by pseeth** [interactiveaudiolab/nussl#85]
Don't automatically write to a file. It should write to the active axis or figure and the user can take care of the plotting outside of nussl.

**Comment by interactiveaudiolab** [comment]
We should copy the type of functionality that librosa has for plotting (see: https://librosa.github.io/librosa/generated/librosa.display.specshow.html). Right now nussl does too much

**Comment by pseeth** [comment]
Fixed in py3-networks, will close when merged into master.

**Comment by pseeth** [comment]
Plotting is now restricted to a few functions and follows what was suggested above.
