### ISSUE TITLE
remove .wav .pyc files

### ISSUE THREAD

**Issue by nkundiushuti** [interactiveaudiolab/nussl#90]
In my opinion, it is not a good idea to include big .wav files (takes a long time to clone and the repository is too big)
similarly, pyc files are system dependent
this should be solved with a gitignore

**Comment by ethman** [comment]
Yeah, .pyc files shouldn't have been included. They're in the .gitignore, and I wasn't able to find any in the master branch. Have you found them elsewhere in the repo?

The .wav files, while big, are necessary for our benchmark testing. We might be able to find a solution where we store them in a separate branch for testing and have a smaller branch for cloning. I'm going to close this issue and open another to that effect.

Please reopen this if you find any straggling .pyc files.
