### ISSUE TITLE
NMF not declared as module in __init__ of nussl

### ISSUE THREAD

**Issue by nkundiushuti** [interactiveaudiolab/nussl#92]
Traceback (most recent call last):
  File "demo_nmf1.py", line 39, in <module>
    simple_example()
  File "demo_nmf1.py", line 19, in simple_example
    nmf = nussl.NMF(nBases)
AttributeError: 'module' object has no attribute 'NMF'

**Comment by ethman** [comment]
This is now fixed in the `fixing_imports` branch and will be propagated to the others shorty. Closing for now.
