### ISSUE TITLE
Provide separate store for large .wav files

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/nussl#93]
As @nkundiushuti mentioned in #90, this project will get to big to clone if it includes too many .wav files. We need to find a sustainable solution for storing benchmark files for tests.

Perhaps another branch is the option.

**Comment by pseeth** [comment]
One simple solution is to use Git Large File Storage.

**Comment by ethman** [comment]
Large files (`*.wav`, `*.npy`, `*.mat`, `*.png`) now tracked on Git LFS. On DEV.

**Comment by ethman** [comment]
git clone (even with LFS) still pulls about 430Mb of audio data. Need to reconfigure LFS.

**Comment by ethman** [comment]
Okay, this _does_ work, but the error messages from git lfs are confusing. I'll write a few sentences in the README to clarify.
