### ISSUE TITLE
utils find_peak_indices() has an off-by-one error

### ISSUE THREAD

**Issue by ethman** [interactiveaudiolab/nussl#96]
Actually, both `find_peak_indices()` and `find_peak_values()` have this bug. But the issue is in `_set_array_zero_indices()`, which both functions use. When fixing this issue, make sure to double check the effect changing this function has on algorithms that use it (perhaps DUET, REPET?)

**Comment by pseeth** [comment]
Think I fixed this. It's covered under unit-tests now.
