### ISSUE TITLE
Problem in function nmf_mfcc

### ISSUE THREAD

**Issue by BigeyeDestroyer** [interactiveaudiolab/nussl#99]
#### Description
I think there is a problem in line 239, 240 of the function "nmf_mfcc". Maybe you should set templates[:, i] = templates_matrix[:, i] when i is in source_indices. 

#### Steps/Code to Reproduce
Current version is:
```python
templates_mask[:, i] = 0 if i in source_indices else templates_matrix[:, i]
activation_mask[i, :] = 0 if i in source_indices else activation_matrix[i, :]
```
However, I think the correct version should be:
```python
templates_mask[:, i] = templates_matrix[:, i] if i in source_indices else 0
activation_mask[i, :] = activation_matrix[i, :] if i in source_indices else 0
```
#### Expected Results
I have not yet carried out any experiments, I will try this on my dataset and see what happens.

**Comment by ethman** [comment]
Hi BigeyeDestroyer, thanks for using nussl. I'm having some trouble understanding the issue that you're describing. Could you provide more detail and context? Also, please use the [issue template](https://raw.githubusercontent.com/interactiveaudiolab/nussl/master/ISSUE_TEMPLATE.md) when adding issues.

**Comment by BigeyeDestroyer** [comment]
Thank you for the reminder, I will modify my issue to make more clear.

**Comment by ethman** [comment]
Ah, yes, I see what you're saying. The logic is backwards here. Thanks for the heads up. I've got a fix that I'll push soon.

**Comment by pseeth** [comment]
Should be fixed in TimbreClustering, which is much more stable and covered by unit tests.
